version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "release-1.x"
    reviewers:
      - "opennms/dependabot-reviewers-maven"
    labels:
      - "dependency update"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
