version: 2.1

executors:
  build-executor:
    docker:
      - image: cimg/openjdk:17.0.14

orbs:
  branch-management: opennms/branch-management@2.3.0

commands:
  run-build:
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Compile and run the tests
          command: |
            mvn clean package
            mvn -DskipITs=false test failsafe:integration-test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find ~/junit -name failsafe-summary.xml -exec rm -f {} \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: cli/target/org.opennms.core.wsman.cli-*.jar

  cached-checkout:
    steps:
      # Restore source cache
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      # Save source cache
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

jobs:
  build:
    executor: build-executor

    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - cached-checkout
      - run-build

  merge:
    executor: build-executor
    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - cached-checkout
      - branch-management/merge-branch:
          committer_email: "cicd-system@opennms.com"
          committer_name: "CI/CD System"
          from: release-1.x
          to: master
      - run-build
      - run:
          name: "Push to Main"
          command: git push --no-verify origin master:master


workflows:
  build-deploy:
    jobs:
      - build
      - merge:
          requires:
            - build
          filters:
            branches:
              only:
               - /^release-.*/
