version: 2

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.14

    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Compile and run the tests
          command: |
            mvn clean package
            mvn -DskipITs=false test failsafe:integration-test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find ~/junit -name failsafe-summary.xml -exec rm -f {} \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: cli/target/org.opennms.core.wsman.cli-*.jar

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

